name: Lint

on:
  pull_request:
    paths:
      - 'services/**'
      - 'libs/**'
      - 'models/**'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true
          cache-dependency-path: |
            'go.work.sum'
            '**/go.sum'

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run gofmt check
        run: go fmt ./... | tee fmt.out && test -z "$(cat fmt.out)"

      - name: Run go vet
        run: |
          go vet ./models/...
          go vet ./services/connectors/...

      - name: Run golangci-lint
        run: golangci-lint run ./...
